image: fedora:latest

before_script:
  - dnf update -y
  - dnf install -y acl gawk which fakeroot rpm-build wget fedpkg gcc gcc-c++ make
  - umask 0022

build_rpm:
  stage: build
  script:
    - wget https://api.github.com/repos/GrapheneOS/hardened_malloc/tarball/11
    - echo "f84f2bc3ee23630c57475dd4fa40d9a0204a40065e86c1a9f10c8c3b379af14d  11" | sha256sum -c
    - fedpkg --release f36 local
  artifacts:
    paths:
        - x86_64/hardened_malloc*.x86_64.rpm
        - hardened_malloc*.src.rpm
